export const CHART_FIND_NAME_SENSOR_SUCCESS  = 'CHART_FIND_NAME_SENSOR_SUCCESS'
export const CHART_FIND_NAME_SENSOR_FALL  = 'CHART_FIND_NAME_SENSOR_FALL'

export const CHART_DATA_SENSOR_SUCCESS  = 'CHART_DATA_SENSOR_SUCCESS'
export const CHART_DATA_SENSOR_FALL  = 'CHART_DATA_SENSOR_FALL'

export const CHART_DATA_ONE_SENSOR_SUCCESS  = 'CHART_DATA_ONE_SENSOR_SUCCESS'
export const CHART_DATA_ONE_SENSOR_FALL  = 'CHART_DATA_ONE_SENSOR_FALL'

export const CHART_DATA_SENSOR_2_SUCCESS  = 'CHART_DATA_SENSOR_2_SUCCESS'
export const CHART_DATA_SENSOR_2_FALL  = 'CHART_DATA_SENSOR_2_FALL'

export const CHART_DATA_ONE_SENSOR_2_SUCCESS  = 'CHART_DATA_ONE_SENSOR_2_SUCCESS'
export const CHART_DATA_ONE_SENSOR_2_FALL  = 'CHART_DATA_ONE_SENSOR_2_FALL'

export const CHART_POWER_SUCCESS  = 'CHART_POWER_SUCCESS'
export const CHART_POWER_FALL  = 'CHART_POWER_FALL'