export const MODAL_ADD_ROOM_SUCCESS  = 'MODAL_ADD_ROOM_SUCCESS'
export const MODAL_ADD_ROOM_FALL  = 'MODAL_ADD_ROOM_FALL'

export const MODAL_ADD_DEVICE_SUCCESS  = 'MODAL_ADD_DEVICE_SUCCESS'
export const MODAL_ADD_DEVICE_FALL  = 'MODAL_ADD_DEVICE_FALL'

export const MODAL_ADD_SENSOR_SUCCESS  = 'MODAL_ADD_SENSOR_SUCCESS'
export const MODAL_ADD_SENSOR_FALL  = 'MODAL_ADD_SENSOR_FALL'

export const MODAL_ADD_USER_SUCCESS  = 'MODAL_ADD_USER_SUCCESS'
export const MODAL_ADD_USER_FALL  = 'MODAL_ADD_USER_FALL'

export const MODAL_ICON_SUCCESS  = 'MODAL_ICON_SUCCESS'
export const MODAL_ICON_FALL  = 'MODAL_ICON_FALL'

export const MODAL_FACE_ID_SUCCESS  = 'MODAL_FACE_ID_SUCCESS'
export const MODAL_FACE_ID_FALL  = 'MODAL_FACE_ID_FALL'
