export const ROOM_LIST_SUCCESS  = 'ROOM_LIST_SUCCESS'
export const ROOM_LIST_FALL  = 'ROOM_LIST_FALL'

export const ROOM_DATA_REQUEST = 'ROOM_DATA_REQUEST'
export const ROOM_DATA_SUCCESS  = 'ROOM_DATA_SUCCESS'
export const ROOM_DATA_FALL   = 'ROOM_DATA_]FALL'

export const ROOM_DEVICE_REQUEST = 'ROOM_DATA_REQUEST'
export const ROOM_DEVICE_SUCCESS  = 'ROOM_DEVICE_SUCCESS'
export const ROOM_DEVICE_FALL  = 'ROOM_DEVICE_FALL'

export const ROOM_SWITCH_SUCCESS = 'ROOM_SWITCH_SUCCESS'
export const ROOM_SWITCH_FALL = 'ROOM_SWITCH_FALL'