export const USER_LOGIN_SUCCESS  = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FALL  = 'USER_LOGIN_FALL'

export const USER_REGISTER_SUCCESS  = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FALL  = 'USER_REGISTER_FALL'